import{a as w,S as v,i as c}from"./assets/vendor-DuKcLXOA.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&d(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const q="56293806-02168ee71cd5fd65309551948";async function u(o,e){return(await w.get("https://pixabay.com/api/",{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const p=document.querySelector(".gallery"),f=document.querySelector(".loader");let S=new v(".gallery a",{captionsData:"alt",captionDelay:250});function M(){p.innerHTML=""}function h(){f.classList.remove("is-hidden")}function m(){f.classList.add("is-hidden")}function y(o){const e=o.map(s=>`
        <li class="gallery-item">
        <a href="${s.largeImageURL}">
            <img src="${s.webformatURL}" alt="${s.tags}" />
            </a>
            <div class="info">
  <p><b>Likes</b><span>${s.likes}</span></p>
  <p><b>Views</b><span>${s.views}</span></p>
  <p><b>Comments</b><span>${s.comments}</span></p>
  <p><b>Downloads</b><span>${s.downloads}</span></p>
</div>
        </li>
        `).join("");p.insertAdjacentHTML("beforeend",e),S.refresh()}const g=document.querySelector(".load-more");function L(){g.classList.remove("is-hidden")}function b(){g.classList.add("is-hidden")}const P=document.querySelector(".form"),$=document.querySelector(".load-more");let a="",n=1,l=0;P.addEventListener("submit",B);$.addEventListener("click",O);async function B(o){if(o.preventDefault(),a=o.target.elements["search-text"].value.trim(),!a){c.show({message:"Please enter a search query.",position:"topRight",color:"red"});return}n=1,M(),b(),h();try{const e=await u(a,n);if(e.hits.length===0){c.show({message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",color:"red"});return}y(e.hits),l=Math.ceil(e.totalHits/15),n<l&&L()}catch(e){console.error("Error fetching images:",e)}finally{m()}}async function O(){n+=1,h(),b();try{const o=await u(a,n);y(o.hits),n<l?L():c.show({message:"You've reached the end of search results.",position:"topRight",color:"blue"}),R()}catch(o){console.error("Error fetching images:",o)}finally{m()}}function R(){const o=document.querySelector(".gallery-item");if(!o)return;const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
