import{a as w,S as v,i as n}from"./assets/vendor-DuKcLXOA.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const S="56293806-02168ee71cd5fd65309551948";async function u(o,e){return(await w.get("https://pixabay.com/api/",{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".loader");let q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function P(){p.innerHTML=""}function f(){h.classList.remove("is-hidden")}function g(){h.classList.add("is-hidden")}function m(o){const e=o.map(s=>`
        <li class="gallery-item">
        <a href="${s.largeImageURL}">
            <img src="${s.webformatURL}" alt="${s.tags}" />
            </a>
            <div class="info">
  <p><b>Likes</b><span>${s.likes}</span></p>
  <p><b>Views</b><span>${s.views}</span></p>
  <p><b>Comments</b><span>${s.comments}</span></p>
  <p><b>Downloads</b><span>${s.downloads}</span></p>
</div>
        </li>
        `).join("");p.insertAdjacentHTML("beforeend",e),q.refresh()}const y=document.querySelector(".load-more");function b(){y.classList.remove("is-hidden")}function L(){y.classList.add("is-hidden")}const M=document.querySelector(".form"),R=document.querySelector(".load-more");let i="",a=1,c=0;M.addEventListener("submit",$);R.addEventListener("click",E);async function $(o){if(o.preventDefault(),i=o.target.elements["search-text"].value.trim(),!i){n.show({message:"Please enter a search query.",position:"topRight",color:"red"});return}a=1,P(),L(),f();try{const e=await u(i,a);if(e.hits.length===0){n.show({message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",color:"red"});return}m(e.hits),c=Math.ceil(e.totalHits/15),a<c?b():n.info({message:"You've reached the end of search results.",position:"topRight",color:"blue"})}catch(e){console.error("Error fetching images:",e),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}async function E(){a+=1,f(),L();try{const o=await u(i,a);m(o.hits),a<c?b():n.show({message:"You've reached the end of search results.",position:"topRight",color:"blue"}),B()}catch(o){console.error("Error fetching images:",o),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}function B(){const o=document.querySelector(".gallery-item");if(!o)return;const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
